### PR TITLE
Fix database creation issue

### PR DESCRIPTION
**Pull request by lauxjpn**
Fix an issue, where we were always using the (changeable) static variable `JetConfiguration.OleDbDefaultProvider` for database create operations.

Now the provider of the supplied connection (string) is used and the default provider is only used as a fallback.

Addresses https://github.com/bubibubi/EntityFrameworkCore.Jet/issues/36#issuecomment-575973514

### CODE REVIEW

**Comment by lauxjpn** [comment]
The only usage of `System.Data.OleDb` in this PR is in the following lines:
https://github.com/bubibubi/EntityFrameworkCore.Jet/pull/37/files#diff-1d7ecb4ed076fa4f94b1c7b22d580cddR457-R460

So I am basically just using `OleDbConnectionStringBuilder` to extract the provider from the connection string. It looks like the `EntityFramework.Jet.FunctionalTests.ConnectionStringBuilderHelper` methods use the class as well.

What are your concerns regarding the usage of `System.Data.OleDb.OleDbConnectionStringBuilder`?

**Comment by bubibubi** [comment]
About the provider I've try to use always the wrapper. Probably is not a good idea to use both, the wrapper and the OleDb provider.
You can find something similar (usage of OleDb and some internal wrappers) in JetEntityFrameworkProvider (the provider for EF 6). The result is a lot of spaghetti code.

About the tests it's not really important... Probably we will have to delete all the tests and integrate the new tests during conversion to EF Core 3.

**Comment by lauxjpn** [comment]
Okay, I pushed another commit that uses `JetProviderFactory.CreateConnectionStringBuilder()` to get a `DbConnectionStringBuilder` instance and then accesses the `Provider` property through an extension method.

The alternative would have been to fully reimplement `OleDbConnectionStringBuilder`, because `DbConnectionStringBuilder` was created with some bad design decisions and a couple of integral methods are non-virtual and cannot be safely overridden and therefore we unfortunately cannot just wrap an inner object and delegate all the outer object calls to it.
So the full implementation would have needed to be maintained to keep it up-to-date with the original `OleDbConnectionStringBuilder` class, as long as users are able to create connection strings with it the original class (which they are).

BTW, I personally don't think, that directly using `OleDbConnectionStringBuilder` would be an issue, because it *is* the class that is used for generating Jet connection strings and is not going to change (unless we completely want to wrap/replace *all* needed `OleDb` classes with our own `Jet` classes and expose only the latter ones to users).
The implementation I pushed now does not gain anything from using `DbConnectionStringBuilder` over `OleDbConnectionStringBuilder`, because it will always be an `OleDbConnectionStringBuilder` object underneath anyway. It only makes it a bit more complicated because of one more layer of abstraction that does not have any purpose.

What do you think?

**Comment by bubibubi** [comment]
Sorry, you are right on everything. I was sure that I had implemented a JetConnectionStringBuilder in System.Data.Jet but I was wrong.
I have some source code about a JetConnectionStringBuilder but probably I've never committed it. If you think that we should write our own ConnectionStringBuilder please let me know that I can share a starting source code. It's very old and not integrated with DbConnectionStringBuilder but there is a parser that could be useful.

**Comment by lauxjpn** [comment]
I think it really depends on, whether we want to expose all the `Jet` classes to users at some point and encourage (or force them) to use them over the `OleDb` classes.
The question here just is, whether EFCore.Jet would gain anything from that?

As for the `OleDbConnectionStringBuilder` specifically, it already has been implemented in a very general purpose way, that does allow any kind of custom option.
The only benefit of using a specialized `JetConnectionStringBuilder` class I can see would be, that we could explicitly expose all the supported options by Jet as individual properties, which would make them easier discoverable.

So I think this depends on which direction you want to take the provider from a user point of view. 

But this becomes more and more unrelated to the current PR and any usages of `OleDbConnectionStringBuilder` would need to be replaced/refactored anyway, if you want to go the all-custom-classes road. So regarding the issue at hand, I think it would be easier to use `OleDbConnectionStringBuilder` for now and just replace it with a Jet specific implementation later, if that should be necessary.

**Comment by lauxjpn** [comment]
This one might be obsolete now. I'll come back to this after we have ensured running scaffolding and migration tests.

**Pull request merged**
