### PR TITLE
Fix DEFAULT clause for HasDefaultValueSql()

### LINKED ISSUE #18: Issue with column default values
I am testing EFCore.Jet to create a new database patterned on an existing DB that has historically been created by some VB6 code and ADOX.

I have columns with default values which in ADOX would have been created like this (VB6):
    With !Conversion
      Set .ParentCatalog = mcatSample
      .Properties("Nullable") = True
      .Properties("Default") = 0
    End With

In the Migration it looks like this:
// etc.
Conversion = table.Column<short>(nullable: true, defaultValueSql: "0"),

when I run the context.Database.EnsureCreatedAsync()
it fails with a syntax error on the Table create

When I then script the migration, I see that the underlying SQL is this:

CREATE TABLE [TAGLIST] (
    [ID] int NOT NULL IDENTITY,
    [CommDetail1] varchar(255) NULL,
    [CommDetail2] varchar(255) NULL,
    [CommDetail3] varchar(255) NULL,
    [CommDetail4] varchar(255) NULL,
    [CommType] smallint NULL,
    [CommTypeW] smallint NULL,
    **[Conversion] smallint NULL DEFAULT (0),**
    [Description] varchar(128) NULL,
    [EvalScript] text NULL,
    [History] bit NOT NULL,
//etc.

From trial and error, for it to work it seems that DEFAULT (0) needs to be DEFAULT 0

### PR DESCRIPTION
**Pull request by xoniuqe**
Fixes #18

As discussed in #18.
I merged this with the preview 3.1. (This is my first pull request, so I have no real experience in how to proceed)

### CODE REVIEW

**Review by lauxjpn — CHANGES_REQUESTED** [review]
> (This is my first pull request, so I have no real experience in how to proceed)

In that case: Congratulations to your first PR!

Here are two small issues:
* Change the title to something meaningful like `Fix DEFAULT clause for HasDefaultValueSql()`.
* Edit your OP and include the line `Fixes #18`. This will automatically link the PR to the issue and close it, when the PR gets merged.

I had this one also locally fixed but not pushed yet, so I will push some accompanying tests to your PR and will open another PR for the rest.

**Comment by xoniuqe** [comment]
@lauxjpn Thank you for your response. The push from master is an embarassing thing.. I am working too much with SVN and our company does not use feature branches....

**Review by lauxjpn — APPROVED** [review]

**Review by lauxjpn — CHANGES_REQUESTED** [review]
When you push a feature branch, make sure that it is based on top of the latest `master` branch commit.

To do this for your already pushed PR, locally rebase your `master` branch on top of the `upstream:master` branch (if you don't have an `upstream` remote added yet, add one and give it the address of the official Pomelo repository (not your fork), then fetch its commits).

After you rebased your own commit(s) on top of our `master` branch, force-push your features branch (in this case your local `master` branch) to your fork.
Your PR will update automatically.

**Review by lauxjpn — APPROVED** [review]

**Comment by lauxjpn** [comment]
@xoniuqe Thanks for your contribution!

**Pull request merged**
