### PR TITLE
Update to .Net 5

### PR DESCRIPTION
**Pull request by ChrisJollyAU**
The main code compiles and runs. I've used some simple select and update statements and it seems to be fine.

The test projects still need a lot of work

Addresses #98

### CODE REVIEW

**Comment by lauxjpn** [comment]
@ChrisJollyAU Awesome! I'll review it over the weekend, so we can merge it next week.
(Just ping me if I should forget to merge it for some reason.)

**Comment by Edivad99** [comment]
Will there be a merge?

**Comment by lauxjpn** [comment]
@Edivad99 Thanks for pinging me! I was about halve way done checking the PR. I will do the second half this week and then merge it.

**Review by lauxjpn — APPROVED** [review]
I did a couple of minor changes, added some code paths back that were removed but are needed etc.

I will upgrade the tests next.

**Comment by renkazan** [comment]
Hello @lauxjpn, do you have a release date for the .Net 5 compatibility ?

**Comment by ceccacecca** [comment]
Hi, any news about the .NET5 update?

**Comment by lauxjpn** [comment]
Not yet, but we could merge it as "work-in-progress", so you could start using/testing it.

**Comment by bairog** [comment]
> Not yet, but we could merge it as "work-in-progress", so you could start using/testing it.

Hello there! How can I obtaion some test build with EF Core 5 (or even EF Core 6) Support?  Thank you.

**Comment by lauxjpn** [comment]
I have scheduled time on Sunday to fix the tests and merge this.

**Comment by lauxjpn** [comment]
@ChrisJollyAU Thank you for your contribution!

**Comment by ChrisJollyAU** [comment]
@lauxjpn No worries. 
Have started lood at ef6 but it is giving interesting stack traces

**Comment by bairog** [comment]
> Have started lood at ef6 but it is giving interesting stack traces

I've created an issue to track [EF Core 6 progress](https://github.com/bubibubi/EntityFrameworkCore.Jet/issues/111). Suppose "interesting stack traces" that @ChrisJollyAU is talking about is the result of my testing of his test builds [from here](https://github.com/bubibubi/EntityFrameworkCore.Jet/issues/98#issuecomment-991045740). 
Anyway - good luck to you guys, looking forrward for getting EF Core 5 and 6 support soon.

**Comment by lauxjpn** [comment]
We will first release support for EF Core 5, before we make any official advances towards EF Core 6.

**Pull request merged**
